### ISSUE TITLE
You are being copied!

### ISSUE THREAD

**Issue by brianstamper** [doyougnu/Stat_Inference_CourseProj1#1]
Look here:
https://github.com/sreenath1986/Statistical-Inference/tree/master/CourseProject1

As pointed out in this thread:
https://class.coursera.org/statinference-030/forum/thread?thread_id=137

Just thought you'd like to know.

**Comment by doyougnu** [comment]
Hey thanks for the heads up. I'm not really that surprised as I uploaded the code to a public site. I'm really just confused as to why anyone would copy wholesale for what could be a free class, especially when they have all the code right there to draw their own conclusions/work from. Anyway thanks again.
